"""Crição da tabela de rascunho da criação do modelo

Revision ID: 1a2dc1d24975
Revises: 1f8dc4c0b9c8
Create Date: 2024-12-14 21:26:42.248212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2dc1d24975'
down_revision = '1f8dc4c0b9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_start_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], name='fk_component', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='fk_customer', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], name='fk_template', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('component_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_customer', 'customer', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_component', 'component', ['component_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_component', type_='foreignkey')
        batch_op.drop_constraint('fk_customer', type_='foreignkey')
        batch_op.drop_column('component_id')
        batch_op.drop_column('customer_id')

    op.drop_table('draft_start_questionnaire')
    # ### end Alembic commands ###
