"""Created_at nas tabelas e criação das tabelas do questionário.

Revision ID: 1f8dc4c0b9c8
Revises: 
Create Date: 2024-12-07 00:31:53.916015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8dc4c0b9c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('manufacturer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('template_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('template_risk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('template_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_section', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('template_risk', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('template_question', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('manufacturer', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
