"""relacionamento de seção do modelo com componente.

Revision ID: 3dd5ae9386bc
Revises: b8c41a19ebff
Create Date: 2025-01-08 12:02:44.927443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd5ae9386bc'
down_revision = 'b8c41a19ebff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_component', 'component', ['component_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_section', schema=None) as batch_op:
        batch_op.drop_constraint('fk_component', type_='foreignkey')
        batch_op.drop_column('component_id')

    # ### end Alembic commands ###
