"""removendo o relacionamento do rascunho com o rascunho componente

Revision ID: 64cf1260e007
Revises: cfdb5da3660e
Create Date: 2025-01-18 14:58:00.893147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cf1260e007'
down_revision = 'cfdb5da3660e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_questionnaire_component', schema=None) as batch_op:
        batch_op.drop_constraint('fk_draft_start_questionnaire', type_='foreignkey')
        batch_op.drop_column('draft_start_questionnaire_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_questionnaire_component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft_start_questionnaire_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_draft_start_questionnaire', 'draft_start_questionnaire', ['draft_start_questionnaire_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
