"""Atualização do banco

Revision ID: 68e5d3502457
Revises: 6e0ca15afb03
Create Date: 2025-01-05 15:28:42.981097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e5d3502457'
down_revision = '6e0ca15afb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_question', schema=None) as batch_op:
        batch_op.drop_column('risk_level')

    # ### end Alembic commands ###
