"""Pequeno ajuste na tabela de questionarios e de questões

Revision ID: 6e0ca15afb03
Revises: 1a2dc1d24975
Create Date: 2024-12-23 00:42:31.884171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0ca15afb03'
down_revision = '1a2dc1d24975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=False))
        batch_op.alter_column('risk_impact',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('risk_likelihood',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('risk_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('risk_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint('fk_section', type_='foreignkey')
        batch_op.drop_constraint('fk_component', type_='foreignkey')
        batch_op.drop_constraint('fk_customer', type_='foreignkey')
        batch_op.create_foreign_key('fk_section', 'section', ['section_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('questionnaire_section_id')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('component_id')

    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('component_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_customer', 'customer', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_component', 'component', ['component_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.drop_constraint('fk_component', type_='foreignkey')
        batch_op.drop_constraint('fk_customer', type_='foreignkey')
        batch_op.drop_column('component_id')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('questionnaire_section_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_section', type_='foreignkey')
        batch_op.create_foreign_key('fk_customer', 'customer', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_component', 'component', ['component_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_section', 'section', ['questionnaire_section_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('risk_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('risk_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('risk_likelihood',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('risk_impact',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('section_id')

    # ### end Alembic commands ###
