"""removendo o relacionamento do rascunho com o rascunho componente

Revision ID: 99b0384a1c65
Revises: 64cf1260e007
Create Date: 2025-01-18 16:04:43.640629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b0384a1c65'
down_revision = '64cf1260e007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_questionnaire_component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft_start_questionnaire_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_draft_start_questionnaire', 'draft_start_questionnaire', ['draft_start_questionnaire_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('draft_start_questionnaire', schema=None) as batch_op:
        batch_op.drop_constraint('fk_draft_questionnaire_component', type_='foreignkey')
        batch_op.drop_column('draft_questionnaire_component_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_start_questionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft_questionnaire_component_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_draft_questionnaire_component', 'draft_questionnaire_component', ['draft_questionnaire_component_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('draft_questionnaire_component', schema=None) as batch_op:
        batch_op.drop_constraint('fk_draft_start_questionnaire', type_='foreignkey')
        batch_op.drop_column('draft_start_questionnaire_id')

    # ### end Alembic commands ###
