"""Colocando nome nas fks

Revision ID: 9cc98f413d6e
Revises: 
Create Date: 2024-11-29 19:30:00.484752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc98f413d6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_solution', 'solution', ['solution_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('manufacturer', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('solution', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_manufacturer', 'manufacturer', ['manufacturer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('template_list_item', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_list', 'template_list', ['template_list_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('template_question', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_section', 'template_section', ['section_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('template_risk', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_template', 'template', ['template_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_question', 'template_question', ['template_question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('template_section', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_template', 'template', ['template_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_section', schema=None) as batch_op:
        batch_op.drop_constraint('fk_template', type_='foreignkey')
        batch_op.create_foreign_key(None, 'template', ['template_id'], ['id'])

    with op.batch_alter_table('template_risk', schema=None) as batch_op:
        batch_op.drop_constraint('fk_question', type_='foreignkey')
        batch_op.drop_constraint('fk_template', type_='foreignkey')
        batch_op.create_foreign_key(None, 'template', ['template_id'], ['id'])
        batch_op.create_foreign_key(None, 'template_question', ['template_question_id'], ['id'])

    with op.batch_alter_table('template_question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_section', type_='foreignkey')
        batch_op.create_foreign_key(None, 'template_section', ['section_id'], ['id'])

    with op.batch_alter_table('template_list_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_list', type_='foreignkey')
        batch_op.create_foreign_key(None, 'template_list', ['template_list_id'], ['id'])

    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.drop_constraint('fk_manufacturer', type_='foreignkey')
        batch_op.create_foreign_key(None, 'manufacturer', ['manufacturer_id'], ['id'])

    with op.batch_alter_table('manufacturer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])

    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_constraint('fk_solution', type_='foreignkey')
        batch_op.create_foreign_key(None, 'solution', ['solution_id'], ['id'])

    # ### end Alembic commands ###
