"""Relacionamento seção com componente e rascunho com multiplos componentes.

Revision ID: cfdb5da3660e
Revises: ec0f954755ed
Create Date: 2025-01-18 14:49:49.905653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdb5da3660e'
down_revision = 'ec0f954755ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_questionnaire_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('component_amount', sa.Integer(), nullable=True),
    sa.Column('draft_start_questionnaire_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], name='fk_component', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_start_questionnaire_id'], ['draft_start_questionnaire.id'], name='fk_draft_start_questionnaire', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_start_questionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft_questionnaire_component_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_component', type_='foreignkey')
        batch_op.create_foreign_key('fk_draft_questionnaire_component', 'draft_questionnaire_component', ['draft_questionnaire_component_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('component_id')

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_component', 'component', ['component_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_constraint('fk_component', type_='foreignkey')
        batch_op.drop_column('component_id')

    with op.batch_alter_table('draft_start_questionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_draft_questionnaire_component', type_='foreignkey')
        batch_op.create_foreign_key('fk_component', 'component', ['component_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('draft_questionnaire_component_id')

    op.drop_table('draft_questionnaire_component')
    # ### end Alembic commands ###
