"""Ajuste template_response_type como nullable na tabela template_risk

Revision ID: f8c883974a59
Revises: fe7d9d11e606
Create Date: 2024-12-02 11:52:17.660574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c883974a59'
down_revision = 'fe7d9d11e606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_risk', schema=None) as batch_op:
        batch_op.alter_column('template_response_type',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_risk', schema=None) as batch_op:
        batch_op.alter_column('template_response_type',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
