"""Ajuste na tabela template_risk

Revision ID: fe7d9d11e606
Revises: 9cc98f413d6e
Create Date: 2024-12-01 02:08:01.452652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7d9d11e606'
down_revision = '9cc98f413d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('template_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_list_id'], ['template_list.id'], name='fk_list', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template_risk', schema=None) as batch_op:
        batch_op.alter_column('risk_impact',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('risk_likelihood',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_risk', schema=None) as batch_op:
        batch_op.alter_column('risk_likelihood',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('risk_impact',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    op.drop_table('template_list_item')
    op.drop_table('template_list')
    # ### end Alembic commands ###
